---

- hosts: test
  become_method: sudo

  vars_prompt:
    - name: usermail
      prompt: "What is your mail?"
      private: no
    - name: epitech
      prompt: "Are you an Epitech student? (yes/no)"
      private: no
      default: "no"
    - name: sshKey
      prompt: "Do you need a new SSH-Key ? (yes/no)"
      private: no
      default: "no"

  tasks:
    - name: Include variables
      include_vars:
        file: variables.yml
        name: params
      vars:
        username:

    - name: Get username
      local_action: command whoami
      register: username

    - include: ./installation/devEnvInstallation.yml
    - include: ./installation/userEnvInstallation.yml
    - include: ./installation/configuration.yml

    - include: ./installation/epitechEnvInstallation.yml
      when: epitech == "yes"
